---
title: "rmv8_induction"
output: html_document
date: "2024-08-06"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reshape2)
library(ggplot2)
library(dplyr)

condition_palette <- c(
  "No supplement" = "grey",
  "Mitomycin C" = "#8491B4FF",
  "Mitomycin C 0.5" = "lightsteelblue",
  "Mitomycin C 1" = "#8491B4FF",
  "Mitomycin C 2" = "#3C5488FF",
  "CSP" = "#F39B7FFF",
  "CSP 1" = "#F39B7FFF",
  "CSP 2" = "#B94E49",
  "CSP 4" = "#7F0012",
  "Hydrogen peroxide" = "yellowgreen"
)

mutant_palette_8 <- c(
  '"RMV8"[rare]' = "magenta",
  '"RMV8"[rare]~Delta*"PRCI"~"1"' = "purple",
  '"RMV8"[rare]~Delta*"PRCI"~"2"' = "violet",
  '"RMV8"[rare]~prophage::cat' = "#1AFF1A", 
  '"RMV8"[rare]~prophage::cat~Delta*"PRCI"~"1"' = "#B3D60D", 
  '"RMV8"[rare]~prophage::cat~Delta*"PRCI"~"2"' = "#FFC107"
)

mutant_labels_8 <- c(
  '"RMV8"[rare]' = ''~"RMV8"["rare"]~'',
  '"RMV8"[rare]~Delta*"PRCI"~"1"' = ''~"RMV8"["rare"]~Delta*"PRCI"~"1"~'',
  '"RMV8"[rare]~Delta*"PRCI"~"2"' = ''~"RMV8"["rare"]~Delta*"PRCI"~"2"~'',
  '"RMV8"[rare]~prophage::cat' = ''~"RMV8"["rare"]~italic("prophage::cat")~'',
  '"RMV8"[rare]~prophage::cat~Delta*"PRCI"~"1"' = ''~"RMV8"["rare"]~italic("prophage::cat")~Delta*"PRCI"~"1"~'', 
  '"RMV8"[rare]~prophage::cat~Delta*"PRCI"~"2"' = ''~"RMV8"["rare"]~italic("prophage::cat")~Delta*"PRCI"~"2"~'' 
)

g <- guide_legend(nrow = 1,
                  title.position = NULL)

```

## Effect of MMC on prophage mutant

```{r mmc procat}

RMV8_procat_mmc_2_growth <- read.csv(file="Desktop/ICL/PJ2- Nic/growth curves/procat_mmc_2_growth.csv",head=TRUE,sep=",",row.names=NULL, na.strings ='#DIV/0!')

processed_RMV8_procat_mmc_2_growth <-
  RMV8_procat_mmc_2_growth %>% 
  tidyr::pivot_longer(-Time,names_to = "Condition",values_to = "OD600") %>% #assign column with name to "condition" and those with values to "OD600"
  tidyr::separate(Condition,sep = '\\.',into = c("Condition","Replicate")) %>% #as name will be Media, Media1, Media2, this is used to remove the numbers and indicate which replicate they are /
  dplyr::mutate(Replicate = dplyr::if_else(is.na(Replicate),"0",Replicate)) %>% #if no number, replace with "0"
  dplyr::mutate(Condition =
                  dplyr::case_when(
                    Condition == "Media" ~ "No supplement",
                    Condition == "MMC0" ~ "Mitomycin C 0.5",
                    Condition == "MMCX1" ~ "Mitomycin C 1",
                    Condition == "MMCX2" ~ "Mitomycin C 2"
                  )
  ) %>%
  dplyr::mutate(Variant = "RMV8R prophage_cat") %>%
  dplyr::group_by(Time,Condition,Variant) %>% #group them by time and condition 
  dplyr::summarise(
    median_OD600 = median(OD600),
    min_OD600 = min(OD600),
    max_OD600 = max(OD600)
  ) %>% 
  dplyr::ungroup() %>%
  tidyr::separate(Time,
                  sep = ':',
                  into = c("Hours","Minutes","Seconds")) %>%
  dplyr::mutate(Hours = as.numeric(as.character(Hours))) %>%
  dplyr::mutate(Minutes = dplyr::if_else(Minutes == 30, 0.5, 0)) %>%
  dplyr::mutate(Time = Hours+Minutes) %>%
  dplyr::select(-Hours,-Minutes,-Seconds)
ggplot(processed_RMV8_procat_mmc_2_growth,
       aes(x = Time,
           y = median_OD600,
           ymin = min_OD600,
           ymax = max_OD600,
           colour = Condition,
           fill = Condition,
           group = interaction(Variant,Condition)
       )
) +
  geom_ribbon(alpha = 0.5, linetype = 0) +
  geom_line() +
  ylab(expression(OD[600])) +
  xlab("Time (h)") +
  scale_colour_manual(values = condition_palette,
                      aesthetics = c("fill","colour")) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8)) +
  guides(colour = g, fill = g)
```

```{r mmc proprci}
RMV8_procat_prci_mmc_2_growth <- read.csv(file="Desktop/ICL/PJ2- Nic/growth curves/procat_prci_mmc_2_growth.csv",head=TRUE,sep=",",row.names=NULL, na.strings ='#DIV/0!')

processed_RMV8_procat_prci_mmc_2_growth <-
  RMV8_procat_prci_mmc_2_growth %>% 
  tidyr::pivot_longer(-Time,names_to = "Condition",values_to = "OD600") %>% #assign column with name to "condition" and those with values to "OD600"
  tidyr::separate(Condition,sep = '\\.',into = c("Condition","Replicate")) %>% #as name will be Media, Media1, Media2, this is used to remove the numbers and indicate which replicate they are /
  dplyr::mutate(Replicate = dplyr::if_else(is.na(Replicate),"0",Replicate)) %>% #if no number, replace with "0"
  dplyr::mutate(Condition =
                  dplyr::case_when(
                    Condition == "Media" ~ "No supplement",
                    Condition == "MMC0" ~ "Mitomycin C 0.5",
                    Condition == "MMCX1" ~ "Mitomycin C 1",
                    Condition == "MMCX2" ~ "Mitomycin C 2"
                  )
  ) %>%
  dplyr::mutate(Variant = "RMV8R prophage_cat_PRCI_mutant") %>%
  dplyr::group_by(Time,Condition,Variant) %>% #group them by time and condition 
  dplyr::summarise(
    median_OD600 = median(OD600),
    min_OD600 = min(OD600),
    max_OD600 = max(OD600)
  ) %>% 
  dplyr::ungroup() %>%
  tidyr::separate(Time,
                  sep = ':',
                  into = c("Hours","Minutes","Seconds")) %>%
  dplyr::mutate(Hours = as.numeric(as.character(Hours))) %>%
  dplyr::mutate(Minutes = dplyr::if_else(Minutes == 30, 0.5, 0)) %>%
  dplyr::mutate(Time = Hours+Minutes) %>%
  dplyr::select(-Hours,-Minutes,-Seconds)

ggplot(processed_RMV8_procat_prci_mmc_2_growth,
       aes(x = Time,
           y = median_OD600,
           ymin = min_OD600,
           ymax = max_OD600,
           colour = Condition,
           fill = Condition,
           group = interaction(Variant,Condition)
       )
) +
  geom_ribbon(alpha = 0.5, linetype = 0) +
  geom_line() +
  ylab(expression(OD[600])) +
  xlab("Time (h)") +
  scale_colour_manual(values = condition_palette,
                      aesthetics = c("fill","colour")) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8)) +
  guides(colour = g, fill = g)
```

```{r mmc tvr}
RMV8_tvr_mmc_growth <- read.csv(file="Desktop/ICL/PJ2- Nic/growth curves/tvr_mmc_growth.csv",head=TRUE,sep=",",row.names=NULL, na.strings ='#DIV/0!')

processed_RMV8_tvr_mmc_growth <-
  RMV8_tvr_mmc_growth %>% 
  tidyr::pivot_longer(-Time,names_to = "Condition",values_to = "OD600") %>% #assign column with name to "condition" and those with values to "OD600"
  tidyr::separate(Condition,sep = '\\.',into = c("Condition","Replicate")) %>% #as name will be Media, Media1, Media2, this is used to remove the numbers and indicate which replicate they are /
  dplyr::mutate(Replicate = dplyr::if_else(is.na(Replicate),"0",Replicate)) %>% #if no number, replace with "0"
  dplyr::mutate(Condition =
                  dplyr::case_when(
                    Condition == "Media" ~ "No supplement",
                    Condition == "MMC0" ~ "Mitomycin C 0.5",
                    Condition == "MMCX1" ~ "Mitomycin C 1",
                    Condition == "MMCX2" ~ "Mitomycin C 2"
                  )
  ) %>%
  dplyr::mutate(Variant = "RMV8R") %>%
  dplyr::group_by(Time,Condition,Variant) %>% #group them by time and condition 
  dplyr::summarise(
    median_OD600 = median(OD600),
    min_OD600 = min(OD600),
    max_OD600 = max(OD600)
  ) %>% 
  dplyr::ungroup() %>%
  tidyr::separate(Time,
                  sep = ':',
                  into = c("Hours","Minutes","Seconds")) %>%
  dplyr::mutate(Hours = as.numeric(as.character(Hours))) %>%
  dplyr::mutate(Minutes = dplyr::if_else(Minutes == 30, 0.5, 0)) %>%
  dplyr::mutate(Time = Hours+Minutes) %>%
  dplyr::select(-Hours,-Minutes,-Seconds)

ggplot(processed_RMV8_tvr_mmc_growth,
       aes(x = Time,
           y = median_OD600,
           ymin = min_OD600,
           ymax = max_OD600,
           colour = Condition,
           fill = Condition,
           group = interaction(Variant,Condition)
       )
) +
  geom_ribbon(alpha = 0.5, linetype = 0) +
  geom_line() +
  ylab(expression(OD[600])) +
  xlab("Time (h)") +
  scale_colour_manual(values = condition_palette,
                      aesthetics = c("fill","colour")) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8)) +
  guides(colour = g, fill = g)
```

```{r mmc tvrprci}
RMV8_tvr_prci_mmc_growth <- read.csv(file="Desktop/ICL/PJ2- Nic/growth curves/tvr_prci_mmc_growth.csv",head=TRUE,sep=",",row.names=NULL, na.strings ='#DIV/0!')

processed_RMV8_tvr_prci_mmc_growth <-
  RMV8_tvr_prci_mmc_growth %>% 
  tidyr::pivot_longer(-Time,names_to = "Condition",values_to = "OD600") %>% #assign column with name to "condition" and those with values to "OD600"
  tidyr::separate(Condition,sep = '\\.',into = c("Condition","Replicate")) %>% #as name will be Media, Media1, Media2, this is used to remove the numbers and indicate which replicate they are /
  dplyr::mutate(Replicate = dplyr::if_else(is.na(Replicate),"0",Replicate)) %>% #if no number, replace with "0"
  dplyr::mutate(Condition =
                  dplyr::case_when(
                    Condition == "Media" ~ "No supplement",
                    Condition == "MMC0" ~ "Mitomycin C 0.5",
                    Condition == "MMCX1" ~ "Mitomycin C 1",
                    Condition == "MMCX2" ~ "Mitomycin C 2"
                  )
  ) %>%
  dplyr::mutate(Variant = "RMV8R PRCI_mutant") %>%
  dplyr::group_by(Time,Condition,Variant) %>% #group them by time and condition 
  dplyr::summarise(
    median_OD600 = median(OD600),
    min_OD600 = min(OD600),
    max_OD600 = max(OD600)
  ) %>% 
  dplyr::ungroup() %>%
  tidyr::separate(Time,
                  sep = ':',
                  into = c("Hours","Minutes","Seconds")) %>%
  dplyr::mutate(Hours = as.numeric(as.character(Hours))) %>%
  dplyr::mutate(Minutes = dplyr::if_else(Minutes == 30, 0.5, 0)) %>%
  dplyr::mutate(Time = Hours+Minutes) %>%
  dplyr::select(-Hours,-Minutes,-Seconds)

ggplot(processed_RMV8_tvr_prci_mmc_growth,
       aes(x = Time,
           y = median_OD600,
           ymin = min_OD600,
           ymax = max_OD600,
           colour = Condition,
           fill = Condition,
           group = interaction(Variant,Condition)
       )
) +
  geom_ribbon(alpha = 0.5, linetype = 0) +
  geom_line() +
  ylab(expression(OD[600])) +
  xlab("Time (h)") +
  scale_colour_manual(values = condition_palette,
                      aesthetics = c("fill","colour")) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8)) +
  guides(colour = g, fill = g)

```

## Effect of CSP on prophage mutant

```{r Prophage cat mutant}

RMV8_procat_csp_growth <- read.csv(file="Desktop/ICL/PJ2- Nic/growth curves/procat_csp_growth.csv",head=TRUE,sep=",",row.names=NULL, na.strings ='#DIV/0!')

processed_RMV8_procat_csp_growth <-
  RMV8_procat_csp_growth %>% 
  tidyr::pivot_longer(-Time,names_to = "Condition",values_to = "OD600") %>% #assign column with name to "condition" and those with values to "OD600"
  tidyr::separate(Condition,sep = '\\.',into = c("Condition","Replicate")) %>% #as name will be Media, Media1, Media2, this is used to remove the numbers and indicate which replicate they are /
  dplyr::mutate(Replicate = dplyr::if_else(is.na(Replicate),"0",Replicate)) %>% #if no number, replace with "0"
  dplyr::mutate(Condition =
                  dplyr::case_when(
                    Condition == "Media" ~ "No supplement",
                    Condition == "CSP" ~ "CSP 1",
                    Condition == "CSPX2" ~ "CSP 2",
                    Condition == "CSPX4" ~ "CSP 4"
                  )
  ) %>%
  dplyr::mutate(Variant = "RMV8R prophage_cat") %>%
  dplyr::group_by(Time,Condition,Variant) %>% #group them by time and condition 
  dplyr::summarise(
    median_OD600 = median(OD600),
    min_OD600 = min(OD600),
    max_OD600 = max(OD600)
  ) %>% 
  dplyr::ungroup() %>%
  tidyr::separate(Time,
                  sep = ':',
                  into = c("Hours","Minutes","Seconds")) %>%
  dplyr::mutate(Hours = as.numeric(as.character(Hours))) %>%
  dplyr::mutate(Minutes = dplyr::if_else(Minutes == 30, 0.5, 0)) %>%
  dplyr::mutate(Time = Hours+Minutes) %>%
  dplyr::select(-Hours,-Minutes,-Seconds)

ggplot(processed_RMV8_procat_csp_growth,
       aes(x = Time,
           y = median_OD600,
           ymin = min_OD600,
           ymax = max_OD600,
           colour = Condition,
           fill = Condition,
           group = interaction(Variant,Condition)
       )
) +
  geom_ribbon(alpha = 0.5, linetype = 0) +
  geom_line() +
  ylab(expression(OD[600])) +
  xlab("Time (h)") +
  scale_colour_manual(values = condition_palette,
                      aesthetics = c("fill","colour")) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8)) +
  guides(colour = g, fill = g)

```

```{r csp proprci}
RMV8_procat_prci_csp_growth <- read.csv(file="Desktop/ICL/PJ2- Nic/growth curves/procat_prci_csp_growth.csv",head=TRUE,sep=",",row.names=NULL, na.strings ='#DIV/0!')

processed_RMV8_procat_prci_csp_growth <-
  RMV8_procat_prci_csp_growth %>% 
  tidyr::pivot_longer(-Time,names_to = "Condition",values_to = "OD600") %>% #assign column with name to "condition" and those with values to "OD600"
  tidyr::separate(Condition,sep = '\\.',into = c("Condition","Replicate")) %>% #as name will be Media, Media1, Media2, this is used to remove the numbers and indicate which replicate they are /
  dplyr::mutate(Replicate = dplyr::if_else(is.na(Replicate),"0",Replicate)) %>% #if no number, replace with "0"
  dplyr::mutate(Condition =
                  dplyr::case_when(
                    Condition == "Media" ~ "No supplement",
                    Condition == "CSP" ~ "CSP 1",
                    Condition == "CSPX2" ~ "CSP 2",
                    Condition == "CSPX4" ~ "CSP 4"
                  )
  ) %>%
  dplyr::mutate(Variant = "RMV8R prophage_cat_PRCI_mutant") %>%
  dplyr::group_by(Time,Condition,Variant) %>% #group them by time and condition 
  dplyr::summarise(
    median_OD600 = median(OD600),
    min_OD600 = min(OD600),
    max_OD600 = max(OD600)
  ) %>% 
  dplyr::ungroup() %>%
  tidyr::separate(Time,
                  sep = ':',
                  into = c("Hours","Minutes","Seconds")) %>%
  dplyr::mutate(Hours = as.numeric(as.character(Hours))) %>%
  dplyr::mutate(Minutes = dplyr::if_else(Minutes == 30, 0.5, 0)) %>%
  dplyr::mutate(Time = Hours+Minutes) %>%
  dplyr::select(-Hours,-Minutes,-Seconds)

ggplot(processed_RMV8_procat_prci_csp_growth,
       aes(x = Time,
           y = median_OD600,
           ymin = min_OD600,
           ymax = max_OD600,
           colour = Condition,
           fill = Condition,
           group = interaction(Variant,Condition)
       )
) +
  geom_ribbon(alpha = 0.5, linetype = 0) +
  geom_line() +
  ylab(expression(OD[600])) +
  xlab("Time (h)") +
  scale_colour_manual(values = condition_palette,
                      aesthetics = c("fill","colour")) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8)) +
  guides(colour = g, fill = g)

```

```{r csp tvr}

RMV8_tvr_csp_growth <- read.csv(file="Desktop/ICL/PJ2- Nic/growth curves/tvr_csp_growth.csv",head=TRUE,sep=",",row.names=NULL, na.strings ='#DIV/0!')

processed_RMV8_tvr_csp_growth <-
  RMV8_tvr_csp_growth %>% 
  tidyr::pivot_longer(-Time,names_to = "Condition",values_to = "OD600") %>% #assign column with name to "condition" and those with values to "OD600"
  tidyr::separate(Condition,sep = '\\.',into = c("Condition","Replicate")) %>% #as name will be Media, Media1, Media2, this is used to remove the numbers and indicate which replicate they are /
  dplyr::mutate(Replicate = dplyr::if_else(is.na(Replicate),"0",Replicate)) %>% #if no number, replace with "0"
  dplyr::mutate(Condition =
                  dplyr::case_when(
                    Condition == "Media" ~ "No supplement",
                    Condition == "CSP" ~ "CSP 1",
                    Condition == "CSPX2" ~ "CSP 2",
                    Condition == "CSPX4" ~ "CSP 4"
                  )
  ) %>%
  dplyr::mutate(Variant = "RMV8R") %>%
  dplyr::group_by(Time,Condition,Variant) %>% #group them by time and condition 
  dplyr::summarise(
    median_OD600 = median(OD600),
    min_OD600 = min(OD600),
    max_OD600 = max(OD600)
  ) %>% 
  dplyr::ungroup() %>%
  tidyr::separate(Time,
                  sep = ':',
                  into = c("Hours","Minutes","Seconds")) %>%
  dplyr::mutate(Hours = as.numeric(as.character(Hours))) %>%
  dplyr::mutate(Minutes = dplyr::if_else(Minutes == 30, 0.5, 0)) %>%
  dplyr::mutate(Time = Hours+Minutes) %>%
  dplyr::select(-Hours,-Minutes,-Seconds)

ggplot(processed_RMV8_tvr_csp_growth,
       aes(x = Time,
           y = median_OD600,
           ymin = min_OD600,
           ymax = max_OD600,
           colour = Condition,
           fill = Condition,
           group = interaction(Variant,Condition)
       )
) +
  geom_ribbon(alpha = 0.5, linetype = 0) +
  geom_line() +
  ylab(expression(OD[600])) +
  xlab("Time (h)") +
  scale_colour_manual(values = condition_palette,
                      aesthetics = c("fill","colour")) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8)) +
  guides(colour = g, fill = g)
```

```{r csp tvrprci}
RMV8_tvr_prci_csp_growth <- read.csv(file="Desktop/ICL/PJ2- Nic/growth curves/tvr_prci_csp_growth.csv",head=TRUE,sep=",",row.names=NULL, na.strings ='#DIV/0!')

processed_RMV8_tvr_prci_csp_growth <-
  RMV8_tvr_prci_csp_growth %>% 
  tidyr::pivot_longer(-Time,names_to = "Condition",values_to = "OD600") %>% #assign column with name to "condition" and those with values to "OD600"
  tidyr::separate(Condition,sep = '\\.',into = c("Condition","Replicate")) %>% #as name will be Media, Media1, Media2, this is used to remove the numbers and indicate which replicate they are /
  dplyr::mutate(Replicate = dplyr::if_else(is.na(Replicate),"0",Replicate)) %>% #if no number, replace with "0"
  dplyr::mutate(Condition =
                  dplyr::case_when(
                    Condition == "Media" ~ "No supplement",
                     Condition == "CSP" ~ "CSP 1",
                    Condition == "CSPX2" ~ "CSP 2",
                    Condition == "CSPX4" ~ "CSP 4"
                  )
  ) %>%
  dplyr::mutate(Variant = "RMV8R PRCI_mutant") %>%
  dplyr::group_by(Time,Condition,Variant) %>% #group them by time and condition 
  dplyr::summarise(
    median_OD600 = median(OD600),
    min_OD600 = min(OD600),
    max_OD600 = max(OD600)
  ) %>% 
  dplyr::ungroup() %>%
  tidyr::separate(Time,
                  sep = ':',
                  into = c("Hours","Minutes","Seconds")) %>%
  dplyr::mutate(Hours = as.numeric(as.character(Hours))) %>%
  dplyr::mutate(Minutes = dplyr::if_else(Minutes == 30, 0.5, 0)) %>%
  dplyr::mutate(Time = Hours+Minutes) %>%
  dplyr::select(-Hours,-Minutes,-Seconds)


ggplot(processed_RMV8_tvr_prci_csp_growth,
       aes(x = Time,
           y = median_OD600,
           ymin = min_OD600,
           ymax = max_OD600,
           colour = Condition,
           fill = Condition,
           group = interaction(Variant,Condition)
       )
) +
  geom_ribbon(alpha = 0.5, linetype = 0) +
  geom_line() +
  ylab(expression(OD[600])) +
  xlab("Time (h)") +
  scale_colour_manual(values = condition_palette,
                      aesthetics = c("fill","colour")) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8)) +
  guides(colour = g, fill = g)

```
